name: Deploy Test Environment

on:
  workflow_dispatch:
  push:
    branches:
      - staging

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: test
      url: ${{ steps.get_url.outputs.app_url }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_TEST }}

      - name: Create appsettings.secrets File
        run: |
          echo "{
            \"connectionstrings\": {
              \"_msg\": \"add any necessary connection string names here, put the strings themselves in appsettings.secrets.json\",
              \"supplysmart-db\": \"${{ secrets.AZURE_SQL_CONNECTION_STRING_TEST }}\"
            }
          }" > SupplySmart.Host/appsettings.secrets.json

      - name: Log in to ACR via Azure CLI
        run: |
          az acr login --name supplysmartacr

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: supplysmartacr.azurecr.io/supplysmart-app:${{ github.sha }}

      - name: Deploy to Azure Container App
        uses: azure/container-apps-deploy-action@v2
        with:
          containerAppName: supplysmart-test
          resourceGroup: rg-supplysmart
          imageToDeploy: supplysmartacr.azurecr.io/supplysmart-app:${{ github.sha }}
          acrName: supplysmartacr
          acrUsername: supplysmartacr
          acrPassword: ${{ secrets.ACR_PASSWORD }}
          containerAppEnvironment: ${{ vars.CONTAINER_APP_ENVIRONMENT }}

      - name: Get Deployment URL
        id: get_url
        run: |
          FQDN=$(az containerapp show \
            --name supplysmart-test \
            --resource-group rg-supplysmart \
            --query properties.configuration.ingress.fqdn \
            -o tsv)
          echo "app_url=https://$FQDN" >> $GITHUB_OUTPUT